name: "Copyparty HA"
description: "Basic homeassistant addon running copyparty"
version: "0.0.1"
slug: "copyparty"
arch:
  - aarch64
  - amd64
startup: services
hassio_api: true
host_network: true
init: false
webui: http://[HOST]:[PORT:3923]/
map:
  - type: share
    read_only: False
    path: /ha/share
  - type: homeassistant_config
    read_only: False
    path: /ha/homeassistant_config
  - type: addon_config
    read_only: False
    path: /ha/addon_config
  - type: ssl
    read_only: False
    path: /ha/ssl
  - type: addons
    read_only: False
    path: /ha/addons
  - type: backup
    read_only: False
    path: /ha/backup
  - type: media
    read_only: False
    path: /ha/media
  - type: data
    read_only: False
    path: /ha/data
  - type: all_addon_configs
    read_only: False
    path: /ha/all_addon_configs

options:
  username: homeassistant
  password: "changeme"

schema:
  username: str
  password: str



# ingress: true
# ingress_port: 3923
# ingress_stream: true